##################################################
# Kafka Service
##################################################  
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
spec:
  selector:
    app: kafka-cluster
  ports:
  - port: 9092
    targetPort: 9092
  type: LoadBalancer
