##################################################
# Zookeeper Service
##################################################  
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
spec:
  selector:
    app: zookeeper-cluster
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888
  clusterIP: None    
