##################################################
# Zookeeper Service
##################################################  
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
spec:
  selector:
    app: zookeeper-cluster
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888
  clusterIP: None    
---
##################################################
# Zookeeper StatefulSet
################################################## 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 3
  serviceName: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.2.1
        imagePullPolicy: Always
        env:
          - name: TZ
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2128"
          - name: ZOOKEEPER_DATA_DIR
            value: "/var/lib/zookeeper/data"
          - name: ZOOKEEPER_LOG_DIR
            value: "/var/lib/zookeeper/log"
          - name: ZOOKEEPER_SERVER_ID
            value: "1"
          - name: ZOOKEEPER_SASL_ENABLED
            value: "FALSE"
        ports:
          - containerPort: 2181
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
      hostname: zookeeper
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zookeeper-pvc
##################################################
# Zookeeper StatefulSet
################################################## 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  replicas: 3
  serviceName: zookeeper-cluster
  selector:
    matchLabels:
      app: zookeeper-cluster
  template:
    metadata:
      labels:
        component: zookeeper-cluster
        app: zookeeper-cluster
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:2.6.0
        securityContext:
          runAsUser: 0 
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  echo $(( $(cat /etc/hosts | grep zookeeper | awk '{print($3)}' | awk '{split($0,array,"-")} END{print array[3]}') + 1 )) > /bitnami/zookeeper/data/myid
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_SERVERS
          value:  crs-zookeeper-0.zookeeper-cluster.default.svc.cluster.local:2888:3888,crs-zookeeper-1.zookeeper-cluster.default.svc.cluster.local:2888:3888,crs-zookeeper-2.zookeeper-cluster.default.svc.cluster.local:2888:3888
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zookeeper-pvc
---
